sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Dr.P3pper!
  minio:
    url: http://localhost:9000
    secret-key: Weak123$
    bucket-name: sky-itcast
    access-key: zqf857
